In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [6]:
data = [[1,2], [3,4]]
data_tensor = torch.tensor(data)
print(data_tensor)
print(data_tensor.dtype)
print(data_tensor.type())

tensor([[1, 2],
        [3, 4]])
torch.int64
torch.LongTensor


#### Creating tensors with zeroes and ones

In [10]:
data_tensor_zero = torch.zeros(2,2)
data_tensor_one = torch.ones(2,2)
print(data_tensor_zero)
print(data_tensor_one)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


#### Creating one tensor from another

In [15]:
data_tensor_two = data_tensor.new_tensor([[2,2], [3,3]])
data_tensor_two_with_property = data_tensor.new_tensor([[2,2], [3,3]], dtype=torch.int8)

In [16]:
print(data_tensor_two)
print(data_tensor_two_with_property)

tensor([[2, 2],
        [3, 3]])
tensor([[2, 2],
        [3, 3]], dtype=torch.int8)


#### Other ways to create tensor

In [17]:
shape = (2,3,)
random_tensor = torch.rand(shape)
print(random_tensor)

tensor([[0.5000, 0.2385, 0.9771],
        [0.4859, 0.0641, 0.1801]])


#### Using Numpy Arrays to create tensors

In [2]:
import numpy as np
import torch
numpy_data = np.random.rand(2,3)
torch_numpy = torch.from_numpy(numpy_data)
torch_numpy_direct = torch.tensor(numpy_data)
print(torch_numpy)
print(torch_numpy_direct)

tensor([[0.8643, 0.5823, 0.0108],
        [0.2378, 0.1611, 0.0913]], dtype=torch.float64)
tensor([[0.8643, 0.5823, 0.0108],
        [0.2378, 0.1611, 0.0913]], dtype=torch.float64)


In [4]:
# put the whole tensor onto CPU for further operations
torch_numpy_direct.cpu().numpy()

array([[0.86432935, 0.58229111, 0.01075149],
       [0.23780171, 0.16109042, 0.09130701]])

#### Operations between tensors

In [5]:
numpy_rand_one = np.random.rand(2,3)
numpy_rand_two = np.random.rand(2,3)
torch_numpy_one = torch.tensor(numpy_rand_one)
torch_numpy_two = torch.tensor(numpy_rand_two)

In [7]:
torch_numpy_three = torch.cat([torch_numpy_one, torch_numpy_two])

In [11]:
# Setting lower and upper bound for any data
torch_numpy_four = torch_numpy_three.clip(0.3,0.7)

In [10]:
torch_numpy_three

tensor([[8.8886e-01, 1.5038e-04, 3.7474e-01],
        [1.6722e-01, 1.0602e-01, 5.5797e-01],
        [9.1181e-01, 7.8382e-01, 6.3626e-01],
        [8.1478e-01, 6.0487e-01, 3.9719e-01]], dtype=torch.float64)

In [13]:
# Multiplication
torch_numpy_three.mul(torch_numpy_four)

tensor([[6.2220e-01, 4.5113e-05, 1.4043e-01],
        [5.0166e-02, 3.1806e-02, 3.1133e-01],
        [6.3826e-01, 5.4867e-01, 4.0483e-01],
        [5.7035e-01, 3.6587e-01, 1.5776e-01]], dtype=torch.float64)

In [15]:
# Matrix Multiplication
torch_numpy_three.matmul(torch_numpy_four) # requires transpose

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [17]:
# .T does transpose
torch_numpy_three.matmul(torch_numpy_four.T)

tensor([[0.7627, 0.4758, 0.8607, 0.7711],
        [0.3580, 0.3933, 0.5463, 0.4028],
        [1.1118, 0.8637, 1.5918, 1.3651],
        [0.9007, 0.6475, 1.2465, 1.0940]], dtype=torch.float64)

In [20]:
# sum of matrix values
sum_in_tensor = torch_numpy_four.sum()
sum_in_python = sum_in_tensor.item()
print(sum_in_tensor)
print(sum_in_python)

tensor(6.2710, dtype=torch.float64)
6.271030869285244


In [22]:
data_tensor_five = torch.arange(20).reshape(5,4)
data_tensor_five

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [25]:
# such operations require values to be in float
data_tensor_five.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [29]:
data_tensor_six = torch.arange(20, dtype=torch.float32).reshape(5,4)
print(data_tensor_six)
print(data_tensor_six.mean())
print(data_tensor_six.mean(dim=0))
print(data_tensor_six.sum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(9.5000)
tensor([ 8.,  9., 10., 11.])
tensor([40., 45., 50., 55.])


#### Autograd in Pytorch / Forward Propogation and Backpropogation
In FP > We compute the loss based on the input

In BP > We compute the gradient of the cost function w.r.t to the input

In [38]:
data_one = torch.tensor([-1.2345, 1.82, -1.07, 0.08, -0.03])
loss = data_one**2 -5
loss

tensor([-3.4760, -1.6876, -3.8551, -4.9936, -4.9991])

In [48]:
# here a gradient function is also included
data_two = torch.tensor([-1.2345, 1.82, -1.07, 0.08, -0.03], requires_grad=True)
loss = data_two**2 -5
loss

tensor([-3.4760, -1.6876, -3.8551, -4.9936, -4.9991], grad_fn=<SubBackward0>)

In [51]:
print(f"Gradient is: {data_two.grad}")

Gradient is: None


In [52]:
# accessing the gradient function
loss.grad_fn

In [53]:
# calculating the gradient using backward propogation?
loss.backward(gradient=torch.ones(5))

In [55]:
data_two.grad

tensor([-2.4690,  3.6400, -2.1400,  0.1600, -0.0600])

In [58]:
# Usually pytorch keeps track of gradients with the DAG, to stop it, it should be explicitly mentioned
data_three_with_tracked_gradients = torch.rand(2,2, requires_grad=True)
data_four_with_not_tracked_gradients = torch.rand(2,2, requires_grad=False)
print(f"tracked: {data_three_with_tracked_gradients.requires_grad}, \
not_tracked: {data_four_with_not_tracked_gradients.requires_grad}")


tracked: True, not_tracked: False


In [59]:
# Another way to do the same
data_five_with_not_tracked_gradients = data_three_with_tracked_gradients.detach()
data_five_with_not_tracked_gradients.requires_grad

False

In [63]:
# Another way to do the same
data_six_with_tracked_gradients = torch.rand(2,2, requires_grad=True)
with torch.no_grad():
    loss = data_six_with_tracked_gradients**2
    print(loss.requires_grad)

False
